export const TARGETS_EXEC_ENABLEMENT_ENV_KEY = "CHIMERA_ENABLE_TARGETS_EXEC";
export const CHECK_REMOTE_ARGV = ["echo", "ok"];
export const DEFAULT_TARGETS_CHECK_TIMEOUT_MS = 30_000;
export const DEFAULT_TARGETS_EXEC_TIMEOUT_MS = 10 * 60 * 1000;
export const DEFAULT_TARGETS_FORWARD_STARTUP_TIMEOUT_MS = 15_000;
